const weatherData_Minsk = {
    currentAt_291224_0915: {
        location: {
            name: "Минск",
            region: "Minsk",
            country: "Беларусь",
            lat: 53.9,
            lon: 27.5667,
            tz_id: "Europe/Minsk",
            localtime_epoch: 1735453680,
            localtime: "2024-12-29 09:28",
        },
        current: {
            last_updated_epoch: 1735452900,
            last_updated: "2024-12-29 09:15",
            temp_c: 0.0,
            temp_f: 32.0,
            is_day: 0,
            condition: { text: "Пасмурно", icon: "//cdn.weatherapi.com/weather/64x64/night/122.png", code: 1009 },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 247,
            wind_dir: "WSW",
            pressure_mb: 1023.0,
            pressure_in: 30.21,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 100,
            cloud: 100,
            feelslike_c: -3.3,
            feelslike_f: 26.0,
            windchill_c: -1.9,
            windchill_f: 28.6,
            heatindex_c: 1.2,
            heatindex_f: 34.2,
            dewpoint_c: 0.6,
            dewpoint_f: 33.0,
            vis_km: 10.0,
            vis_miles: 6.0,
            uv: 0.0,
            gust_mph: 11.3,
            gust_kph: 18.3,
        },
        forecast: {
            forecastday: [
                {
                    date: "2024-12-29",
                    date_epoch: 1735430400,
                    day: {
                        maxtemp_c: 3.4,
                        maxtemp_f: 38.1,
                        mintemp_c: 0.1,
                        mintemp_f: 32.2,
                        avgtemp_c: 2.1,
                        avgtemp_f: 35.7,
                        maxwind_mph: 11.0,
                        maxwind_kph: 17.6,
                        totalprecip_mm: 0.01,
                        totalprecip_in: 0.0,
                        totalsnow_cm: 0.0,
                        avgvis_km: 6.3,
                        avgvis_miles: 3.0,
                        avghumidity: 93,
                        daily_will_it_rain: 0,
                        daily_chance_of_rain: 0,
                        daily_will_it_snow: 0,
                        daily_chance_of_snow: 3,
                        condition: {
                            text: "Пасмурно",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                            code: 1009,
                        },
                        uv: 0.0,
                    },
                    astro: {
                        sunrise: "09:29 AM",
                        sunset: "04:56 PM",
                        moonrise: "08:47 AM",
                        moonset: "02:46 PM",
                        moon_phase: "Waning Crescent",
                        moon_illumination: 4,
                        is_moon_up: 0,
                        is_sun_up: 0,
                    },
                    hour: [
                        {
                            time_epoch: 1735419600,
                            time: "2024-12-29 00:00",
                            temp_c: 2.1,
                            temp_f: 35.7,
                            is_day: 0,
                            condition: {
                                text: "Дымка",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                                code: 1030,
                            },
                            wind_mph: 6.7,
                            wind_kph: 10.8,
                            wind_degree: 239,
                            wind_dir: "WSW",
                            pressure_mb: 1027.0,
                            pressure_in: 30.33,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 95,
                            cloud: 100,
                            feelslike_c: -1.0,
                            feelslike_f: 30.2,
                            windchill_c: -1.0,
                            windchill_f: 30.2,
                            heatindex_c: 2.1,
                            heatindex_f: 35.7,
                            dewpoint_c: 1.4,
                            dewpoint_f: 34.6,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 2.0,
                            vis_miles: 1.0,
                            gust_mph: 10.4,
                            gust_kph: 16.7,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735423200,
                            time: "2024-12-29 01:00",
                            temp_c: 1.4,
                            temp_f: 34.5,
                            is_day: 0,
                            condition: {
                                text: "Дымка",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                                code: 1030,
                            },
                            wind_mph: 6.5,
                            wind_kph: 10.4,
                            wind_degree: 240,
                            wind_dir: "WSW",
                            pressure_mb: 1027.0,
                            pressure_in: 30.32,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 96,
                            cloud: 88,
                            feelslike_c: -1.7,
                            feelslike_f: 28.9,
                            windchill_c: -1.7,
                            windchill_f: 28.9,
                            heatindex_c: 1.4,
                            heatindex_f: 34.5,
                            dewpoint_c: 0.9,
                            dewpoint_f: 33.6,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 2.0,
                            vis_miles: 1.0,
                            gust_mph: 10.5,
                            gust_kph: 16.8,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735426800,
                            time: "2024-12-29 02:00",
                            temp_c: 0.5,
                            temp_f: 32.9,
                            is_day: 0,
                            condition: {
                                text: "Дымка",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                                code: 1030,
                            },
                            wind_mph: 6.3,
                            wind_kph: 10.1,
                            wind_degree: 241,
                            wind_dir: "WSW",
                            pressure_mb: 1026.0,
                            pressure_in: 30.31,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 97,
                            cloud: 88,
                            feelslike_c: -2.7,
                            feelslike_f: 27.1,
                            windchill_c: -2.7,
                            windchill_f: 27.1,
                            heatindex_c: 0.5,
                            heatindex_f: 32.9,
                            dewpoint_c: 0.1,
                            dewpoint_f: 32.1,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 2.0,
                            vis_miles: 1.0,
                            gust_mph: 10.6,
                            gust_kph: 17.1,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735430400,
                            time: "2024-12-29 03:00",
                            temp_c: 0.1,
                            temp_f: 32.2,
                            is_day: 0,
                            condition: {
                                text: "Дымка",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                                code: 1030,
                            },
                            wind_mph: 5.6,
                            wind_kph: 9.0,
                            wind_degree: 242,
                            wind_dir: "WSW",
                            pressure_mb: 1026.0,
                            pressure_in: 30.3,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 97,
                            cloud: 88,
                            feelslike_c: -2.9,
                            feelslike_f: 26.8,
                            windchill_c: -2.9,
                            windchill_f: 26.8,
                            heatindex_c: 0.1,
                            heatindex_f: 32.2,
                            dewpoint_c: -0.3,
                            dewpoint_f: 31.4,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 2.0,
                            vis_miles: 1.0,
                            gust_mph: 9.6,
                            gust_kph: 15.5,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735434000,
                            time: "2024-12-29 04:00",
                            temp_c: 0.4,
                            temp_f: 32.7,
                            is_day: 0,
                            condition: {
                                text: "Дымка",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                                code: 1030,
                            },
                            wind_mph: 5.6,
                            wind_kph: 9.0,
                            wind_degree: 243,
                            wind_dir: "WSW",
                            pressure_mb: 1026.0,
                            pressure_in: 30.29,
                            precip_mm: 0.01,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 95,
                            cloud: 100,
                            feelslike_c: -2.6,
                            feelslike_f: 27.4,
                            windchill_c: -2.6,
                            windchill_f: 27.4,
                            heatindex_c: 0.4,
                            heatindex_f: 32.7,
                            dewpoint_c: -0.2,
                            dewpoint_f: 31.6,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 1,
                            chance_of_snow: 78,
                            vis_km: 2.0,
                            vis_miles: 1.0,
                            gust_mph: 9.3,
                            gust_kph: 14.9,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735437600,
                            time: "2024-12-29 05:00",
                            temp_c: 1.0,
                            temp_f: 33.8,
                            is_day: 0,
                            condition: {
                                text: "Дымка",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                                code: 1030,
                            },
                            wind_mph: 5.4,
                            wind_kph: 8.6,
                            wind_degree: 243,
                            wind_dir: "WSW",
                            pressure_mb: 1025.0,
                            pressure_in: 30.27,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 94,
                            cloud: 93,
                            feelslike_c: -1.8,
                            feelslike_f: 28.8,
                            windchill_c: -1.8,
                            windchill_f: 28.8,
                            heatindex_c: 1.0,
                            heatindex_f: 33.8,
                            dewpoint_c: 0.2,
                            dewpoint_f: 32.3,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 2.0,
                            vis_miles: 1.0,
                            gust_mph: 8.5,
                            gust_kph: 13.8,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735441200,
                            time: "2024-12-29 06:00",
                            temp_c: 1.3,
                            temp_f: 34.3,
                            is_day: 0,
                            condition: {
                                text: "Дымка",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                                code: 1030,
                            },
                            wind_mph: 5.6,
                            wind_kph: 9.0,
                            wind_degree: 244,
                            wind_dir: "WSW",
                            pressure_mb: 1025.0,
                            pressure_in: 30.26,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 94,
                            cloud: 94,
                            feelslike_c: -1.6,
                            feelslike_f: 29.2,
                            windchill_c: -1.6,
                            windchill_f: 29.2,
                            heatindex_c: 1.3,
                            heatindex_f: 34.3,
                            dewpoint_c: 0.4,
                            dewpoint_f: 32.8,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 2.0,
                            vis_miles: 1.0,
                            gust_mph: 9.0,
                            gust_kph: 14.5,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735444800,
                            time: "2024-12-29 07:00",
                            temp_c: 1.5,
                            temp_f: 34.7,
                            is_day: 0,
                            condition: {
                                text: "Дымка",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                                code: 1030,
                            },
                            wind_mph: 5.6,
                            wind_kph: 9.0,
                            wind_degree: 252,
                            wind_dir: "WSW",
                            pressure_mb: 1025.0,
                            pressure_in: 30.26,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 95,
                            cloud: 94,
                            feelslike_c: -1.3,
                            feelslike_f: 29.7,
                            windchill_c: -1.3,
                            windchill_f: 29.7,
                            heatindex_c: 1.5,
                            heatindex_f: 34.6,
                            dewpoint_c: 0.7,
                            dewpoint_f: 33.3,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 2.0,
                            vis_miles: 1.0,
                            gust_mph: 9.1,
                            gust_kph: 14.7,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735448400,
                            time: "2024-12-29 08:00",
                            temp_c: 1.4,
                            temp_f: 34.5,
                            is_day: 0,
                            condition: {
                                text: "Дымка",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
                                code: 1030,
                            },
                            wind_mph: 6.0,
                            wind_kph: 9.7,
                            wind_degree: 252,
                            wind_dir: "WSW",
                            pressure_mb: 1025.0,
                            pressure_in: 30.25,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 95,
                            cloud: 85,
                            feelslike_c: -1.6,
                            feelslike_f: 29.2,
                            windchill_c: -1.6,
                            windchill_f: 29.2,
                            heatindex_c: 1.4,
                            heatindex_f: 34.5,
                            dewpoint_c: 0.7,
                            dewpoint_f: 33.3,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 2.0,
                            vis_miles: 1.0,
                            gust_mph: 10.4,
                            gust_kph: 16.7,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735452000,
                            time: "2024-12-29 09:00",
                            temp_c: 0.0,
                            temp_f: 32.0,
                            is_day: 0,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                code: 1009,
                            },
                            wind_mph: 6.3,
                            wind_kph: 10.1,
                            wind_degree: 247,
                            wind_dir: "WSW",
                            pressure_mb: 1023.0,
                            pressure_in: 30.21,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 100,
                            cloud: 100,
                            feelslike_c: -1.9,
                            feelslike_f: 28.6,
                            windchill_c: -1.9,
                            windchill_f: 28.6,
                            heatindex_c: 1.2,
                            heatindex_f: 34.2,
                            dewpoint_c: 0.6,
                            dewpoint_f: 33.0,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 11.3,
                            gust_kph: 18.3,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735455600,
                            time: "2024-12-29 10:00",
                            temp_c: 2.0,
                            temp_f: 35.7,
                            is_day: 1,
                            condition: {
                                text: "Дымка",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
                                code: 1030,
                            },
                            wind_mph: 6.7,
                            wind_kph: 10.8,
                            wind_degree: 241,
                            wind_dir: "WSW",
                            pressure_mb: 1024.0,
                            pressure_in: 30.25,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 94,
                            cloud: 100,
                            feelslike_c: -1.1,
                            feelslike_f: 30.1,
                            windchill_c: -1.1,
                            windchill_f: 30.1,
                            heatindex_c: 2.0,
                            heatindex_f: 35.7,
                            dewpoint_c: 1.2,
                            dewpoint_f: 34.1,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 2.0,
                            vis_miles: 1.0,
                            gust_mph: 11.1,
                            gust_kph: 17.9,
                            uv: 0.0,
                        },
                        {
                            time_epoch: 1735459200,
                            time: "2024-12-29 11:00",
                            temp_c: 2.9,
                            temp_f: 37.3,
                            is_day: 1,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                code: 1009,
                            },
                            wind_mph: 7.8,
                            wind_kph: 12.6,
                            wind_degree: 240,
                            wind_dir: "WSW",
                            pressure_mb: 1024.0,
                            pressure_in: 30.24,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 91,
                            cloud: 100,
                            feelslike_c: -0.4,
                            feelslike_f: 31.3,
                            windchill_c: -0.4,
                            windchill_f: 31.3,
                            heatindex_c: 2.9,
                            heatindex_f: 37.3,
                            dewpoint_c: 1.7,
                            dewpoint_f: 35.0,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 11.7,
                            gust_kph: 18.8,
                            uv: 0.1,
                        },
                        {
                            time_epoch: 1735462800,
                            time: "2024-12-29 12:00",
                            temp_c: 3.2,
                            temp_f: 37.8,
                            is_day: 1,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                code: 1009,
                            },
                            wind_mph: 8.5,
                            wind_kph: 13.7,
                            wind_degree: 239,
                            wind_dir: "WSW",
                            pressure_mb: 1024.0,
                            pressure_in: 30.23,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 91,
                            cloud: 100,
                            feelslike_c: -0.3,
                            feelslike_f: 31.6,
                            windchill_c: -0.3,
                            windchill_f: 31.6,
                            heatindex_c: 3.2,
                            heatindex_f: 37.8,
                            dewpoint_c: 1.9,
                            dewpoint_f: 35.5,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 12.3,
                            gust_kph: 19.8,
                            uv: 0.2,
                        },
                        {
                            time_epoch: 1735466400,
                            time: "2024-12-29 13:00",
                            temp_c: 3.4,
                            temp_f: 38.1,
                            is_day: 1,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                code: 1009,
                            },
                            wind_mph: 8.9,
                            wind_kph: 14.4,
                            wind_degree: 238,
                            wind_dir: "WSW",
                            pressure_mb: 1023.0,
                            pressure_in: 30.21,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 91,
                            cloud: 100,
                            feelslike_c: -0.1,
                            feelslike_f: 31.7,
                            windchill_c: -0.1,
                            windchill_f: 31.7,
                            heatindex_c: 3.4,
                            heatindex_f: 38.1,
                            dewpoint_c: 2.0,
                            dewpoint_f: 35.7,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 12.8,
                            gust_kph: 20.7,
                            uv: 0.2,
                        },
                        {
                            time_epoch: 1735470000,
                            time: "2024-12-29 14:00",
                            temp_c: 3.4,
                            temp_f: 38.1,
                            is_day: 1,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                code: 1009,
                            },
                            wind_mph: 9.2,
                            wind_kph: 14.8,
                            wind_degree: 233,
                            wind_dir: "SW",
                            pressure_mb: 1023.0,
                            pressure_in: 30.2,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 91,
                            cloud: 100,
                            feelslike_c: -0.2,
                            feelslike_f: 31.7,
                            windchill_c: -0.2,
                            windchill_f: 31.7,
                            heatindex_c: 3.4,
                            heatindex_f: 38.1,
                            dewpoint_c: 2.0,
                            dewpoint_f: 35.7,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 13.4,
                            gust_kph: 21.6,
                            uv: 0.2,
                        },
                        {
                            time_epoch: 1735473600,
                            time: "2024-12-29 15:00",
                            temp_c: 3.3,
                            temp_f: 38.0,
                            is_day: 1,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                code: 1009,
                            },
                            wind_mph: 9.8,
                            wind_kph: 15.8,
                            wind_degree: 223,
                            wind_dir: "SW",
                            pressure_mb: 1022.0,
                            pressure_in: 30.18,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 91,
                            cloud: 100,
                            feelslike_c: -0.5,
                            feelslike_f: 31.2,
                            windchill_c: -0.5,
                            windchill_f: 31.2,
                            heatindex_c: 3.3,
                            heatindex_f: 38.0,
                            dewpoint_c: 1.9,
                            dewpoint_f: 35.5,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 14.9,
                            gust_kph: 23.9,
                            uv: 0.1,
                        },
                        {
                            time_epoch: 1735477200,
                            time: "2024-12-29 16:00",
                            temp_c: 3.2,
                            temp_f: 37.7,
                            is_day: 1,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                code: 1009,
                            },
                            wind_mph: 10.3,
                            wind_kph: 16.6,
                            wind_degree: 222,
                            wind_dir: "SW",
                            pressure_mb: 1022.0,
                            pressure_in: 30.17,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 90,
                            cloud: 100,
                            feelslike_c: -0.8,
                            feelslike_f: 30.7,
                            windchill_c: -0.8,
                            windchill_f: 30.7,
                            heatindex_c: 3.2,
                            heatindex_f: 37.7,
                            dewpoint_c: 1.7,
                            dewpoint_f: 35.1,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 16.1,
                            gust_kph: 25.8,
                            uv: 0.0,
                        },
                        {
                            time_epoch: 1735480800,
                            time: "2024-12-29 17:00",
                            temp_c: 3.0,
                            temp_f: 37.4,
                            is_day: 0,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                code: 1009,
                            },
                            wind_mph: 10.1,
                            wind_kph: 16.2,
                            wind_degree: 230,
                            wind_dir: "SW",
                            pressure_mb: 1022.0,
                            pressure_in: 30.17,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 91,
                            cloud: 100,
                            feelslike_c: -0.9,
                            feelslike_f: 30.3,
                            windchill_c: -0.9,
                            windchill_f: 30.3,
                            heatindex_c: 3.0,
                            heatindex_f: 37.3,
                            dewpoint_c: 1.6,
                            dewpoint_f: 34.9,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 15.9,
                            gust_kph: 25.7,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735484400,
                            time: "2024-12-29 18:00",
                            temp_c: 3.0,
                            temp_f: 37.3,
                            is_day: 0,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                code: 1009,
                            },
                            wind_mph: 10.7,
                            wind_kph: 17.3,
                            wind_degree: 228,
                            wind_dir: "SW",
                            pressure_mb: 1021.0,
                            pressure_in: 30.15,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 91,
                            cloud: 100,
                            feelslike_c: -1.1,
                            feelslike_f: 30.0,
                            windchill_c: -1.1,
                            windchill_f: 30.0,
                            heatindex_c: 3.0,
                            heatindex_f: 37.3,
                            dewpoint_c: 1.7,
                            dewpoint_f: 35.1,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 16.9,
                            gust_kph: 27.1,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735488000,
                            time: "2024-12-29 19:00",
                            temp_c: 2.7,
                            temp_f: 36.8,
                            is_day: 0,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                code: 1009,
                            },
                            wind_mph: 10.7,
                            wind_kph: 17.3,
                            wind_degree: 227,
                            wind_dir: "SW",
                            pressure_mb: 1021.0,
                            pressure_in: 30.14,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 93,
                            cloud: 100,
                            feelslike_c: -1.5,
                            feelslike_f: 29.3,
                            windchill_c: -1.5,
                            windchill_f: 29.3,
                            heatindex_c: 2.7,
                            heatindex_f: 36.8,
                            dewpoint_c: 1.7,
                            dewpoint_f: 35.0,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 17.2,
                            gust_kph: 27.7,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735491600,
                            time: "2024-12-29 20:00",
                            temp_c: 2.5,
                            temp_f: 36.6,
                            is_day: 0,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                code: 1009,
                            },
                            wind_mph: 11.0,
                            wind_kph: 17.6,
                            wind_degree: 227,
                            wind_dir: "SW",
                            pressure_mb: 1020.0,
                            pressure_in: 30.13,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 93,
                            cloud: 100,
                            feelslike_c: -1.7,
                            feelslike_f: 28.9,
                            windchill_c: -1.7,
                            windchill_f: 28.9,
                            heatindex_c: 2.5,
                            heatindex_f: 36.6,
                            dewpoint_c: 1.6,
                            dewpoint_f: 34.8,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 17.5,
                            gust_kph: 28.2,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735495200,
                            time: "2024-12-29 21:00",
                            temp_c: 2.3,
                            temp_f: 36.2,
                            is_day: 0,
                            condition: {
                                text: "Пасмурно",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                code: 1009,
                            },
                            wind_mph: 11.0,
                            wind_kph: 17.6,
                            wind_degree: 228,
                            wind_dir: "SW",
                            pressure_mb: 1020.0,
                            pressure_in: 30.12,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 93,
                            cloud: 96,
                            feelslike_c: -2.0,
                            feelslike_f: 28.5,
                            windchill_c: -2.0,
                            windchill_f: 28.5,
                            heatindex_c: 2.3,
                            heatindex_f: 36.2,
                            dewpoint_c: 1.4,
                            dewpoint_f: 34.5,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 17.7,
                            gust_kph: 28.5,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735498800,
                            time: "2024-12-29 22:00",
                            temp_c: 2.2,
                            temp_f: 36.0,
                            is_day: 0,
                            condition: {
                                text: "Облачно",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                                code: 1006,
                            },
                            wind_mph: 11.0,
                            wind_kph: 17.6,
                            wind_degree: 231,
                            wind_dir: "SW",
                            pressure_mb: 1020.0,
                            pressure_in: 30.11,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 93,
                            cloud: 77,
                            feelslike_c: -2.1,
                            feelslike_f: 28.2,
                            windchill_c: -2.1,
                            windchill_f: 28.2,
                            heatindex_c: 2.2,
                            heatindex_f: 36.0,
                            dewpoint_c: 1.2,
                            dewpoint_f: 34.1,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 17.7,
                            gust_kph: 28.4,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735502400,
                            time: "2024-12-29 23:00",
                            temp_c: 1.9,
                            temp_f: 35.5,
                            is_day: 0,
                            condition: {
                                text: "Переменная облачность",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                code: 1003,
                            },
                            wind_mph: 11.0,
                            wind_kph: 17.6,
                            wind_degree: 236,
                            wind_dir: "WSW",
                            pressure_mb: 1019.0,
                            pressure_in: 30.1,
                            precip_mm: 0.0,
                            precip_in: 0.0,
                            snow_cm: 0.0,
                            humidity: 91,
                            cloud: 57,
                            feelslike_c: -2.5,
                            feelslike_f: 27.6,
                            windchill_c: -2.5,
                            windchill_f: 27.6,
                            heatindex_c: 1.9,
                            heatindex_f: 35.5,
                            dewpoint_c: 0.7,
                            dewpoint_f: 33.2,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10.0,
                            vis_miles: 6.0,
                            gust_mph: 18.1,
                            gust_kph: 29.1,
                            uv: 0,
                        },
                    ],
                },
            ],
        },
    },

    future_060125_210125: {
        time: [
            "2025-01-06T00:00:00.000Z",
            "2025-01-07T00:00:00.000Z",
            "2025-01-08T00:00:00.000Z",
            "2025-01-09T00:00:00.000Z",
            "2025-01-10T00:00:00.000Z",
            "2025-01-11T00:00:00.000Z",
            "2025-01-12T00:00:00.000Z",
            "2025-01-13T00:00:00.000Z",
            "2025-01-14T00:00:00.000Z",
            "2025-01-15T00:00:00.000Z",
            "2025-01-16T00:00:00.000Z",
            "2025-01-17T00:00:00.000Z",
            "2025-01-18T00:00:00.000Z",
            "2025-01-19T00:00:00.000Z",
            "2025-01-20T00:00:00.000Z",
            "2025-01-21T00:00:00.000Z",
        ],
        weatherCode: {
            "0": 73,
            "1": 51,
            "2": 71,
            "3": 73,
            "4": 71,
            "5": 73,
            "6": 71,
            "7": 3,
            "8": 3,
            "9": 51,
            "10": 71,
            "11": 71,
            "12": 3,
            "13": 73,
            "14": 3,
            "15": 1,
        },
        temperature2mMax: {
            "0": 0.8700000047683716,
            "1": 3.869999885559082,
            "2": 3.369999885559082,
            "3": 1.649999976158142,
            "4": 3.3499999046325684,
            "5": -0.949999988079071,
            "6": 2.6500000953674316,
            "7": 1.350000023841858,
            "8": 0.25,
            "9": 1,
            "10": 1.7999999523162842,
            "11": 0.10000000149011612,
            "12": 1.75,
            "13": 2.1500000953674316,
            "14": 0.699999988079071,
            "15": -1.0499999523162842,
        },
        temperature2mMin: {
            "0": -5.329999923706055,
            "1": 1.3200000524520874,
            "2": 0.17000001668930054,
            "3": -3.3499999046325684,
            "4": -0.75,
            "5": -4.199999809265137,
            "6": -8.199999809265137,
            "7": -0.3499999940395355,
            "8": -1,
            "9": -1.2000000476837158,
            "10": -1.2000000476837158,
            "11": -2.5999999046325684,
            "12": -3.1500000953674316,
            "13": 0.10000000149011612,
            "14": -1,
            "15": -4.117500305175781,
        },
        precipitationSum: {
            "0": 3,
            "1": 1.2000000476837158,
            "2": 4.999999523162842,
            "3": 2.5,
            "4": 2.6000003814697266,
            "5": 5.899999618530273,
            "6": 0.10000000149011612,
            "7": 0,
            "8": 0,
            "9": 0.5,
            "10": 1.3000001907348633,
            "11": 0.6000000238418579,
            "12": 0,
            "13": 4.199999809265137,
            "14": 0,
            "15": 0,
        },
        windSpeed10mMax: {
            "0": 21.239999771118164,
            "1": 19.799999237060547,
            "2": 19.799999237060547,
            "3": 16.279802322387695,
            "4": 28.528722763061523,
            "5": 29.037519454956055,
            "6": 23.33344268798828,
            "7": 10.99032211303711,
            "8": 18.723459243774414,
            "9": 24.448213577270508,
            "10": 28.691795349121094,
            "11": 17.462783813476562,
            "12": 15.876774787902832,
            "13": 23.358423233032227,
            "14": 23.675304412841797,
            "15": 9.793059349060059,
        },
        windDirection10mDominant: {
            "0": 146.1313018798828,
            "1": 186.53042602539062,
            "2": 225.8942108154297,
            "3": 177.13389587402344,
            "4": 207.86016845703125,
            "5": 259.13409423828125,
            "6": 357.8300476074219,
            "7": 13.162270545959473,
            "8": 265.5066223144531,
            "9": 253.4291229248047,
            "10": 277.8433532714844,
            "11": 224.4685821533203,
            "12": 185.9016571044922,
            "13": 211.2382049560547,
            "14": 233.06259155273438,
            "15": 218.19097900390625,
        },
    },
};

const weatherData_Pekin = {
    currentAt_291224_1545: {
        location: {
            name: "Пекин",
            region: "Beijing",
            country: "Китай",
            lat: 39.9289,
            lon: 116.3883,
            tz_id: "Asia/Shanghai",
            localtime_epoch: 1735459153,
            localtime: "2024-12-29 15:59",
        },
        current: {
            last_updated_epoch: 1735458300,
            last_updated: "2024-12-29 15:45",
            temp_c: 4,
            temp_f: 39.2,
            is_day: 1,
            condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 180,
            wind_dir: "S",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0,
            precip_in: 0,
            humidity: 23,
            cloud: 0,
            feelslike_c: 3.1,
            feelslike_f: 37.5,
            windchill_c: 2.6,
            windchill_f: 36.6,
            heatindex_c: 3.6,
            heatindex_f: 38.4,
            dewpoint_c: -19.9,
            dewpoint_f: -3.8,
            vis_km: 10,
            vis_miles: 6,
            uv: 0.4,
            gust_mph: 4,
            gust_kph: 6.4,
        },
        forecast: {
            forecastday: [
                {
                    date: "2024-12-29",
                    date_epoch: 1735430400,
                    day: {
                        maxtemp_c: 3.6,
                        maxtemp_f: 38.4,
                        mintemp_c: -2.9,
                        mintemp_f: 26.9,
                        avgtemp_c: -0.3,
                        avgtemp_f: 31.4,
                        maxwind_mph: 6,
                        maxwind_kph: 9.7,
                        totalprecip_mm: 0,
                        totalprecip_in: 0,
                        totalsnow_cm: 0,
                        avgvis_km: 10,
                        avgvis_miles: 6,
                        avghumidity: 23,
                        daily_will_it_rain: 0,
                        daily_chance_of_rain: 0,
                        daily_will_it_snow: 0,
                        daily_chance_of_snow: 0,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        uv: 0.2,
                    },
                    astro: {
                        sunrise: "07:36 AM",
                        sunset: "04:58 PM",
                        moonrise: "06:12 AM",
                        moonset: "03:04 PM",
                        moon_phase: "Waning Crescent",
                        moon_illumination: 4,
                        is_moon_up: 0,
                        is_sun_up: 0,
                    },
                    hour: [
                        {
                            time_epoch: 1735401600,
                            time: "2024-12-29 00:00",
                            temp_c: -1.4,
                            temp_f: 29.4,
                            is_day: 0,
                            condition: {
                                text: "Clear ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                code: 1000,
                            },
                            wind_mph: 2,
                            wind_kph: 3.2,
                            wind_degree: 323,
                            wind_dir: "NW",
                            pressure_mb: 1026,
                            pressure_in: 30.3,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 24,
                            cloud: 11,
                            feelslike_c: -2.2,
                            feelslike_f: 28.1,
                            windchill_c: -2.2,
                            windchill_f: 28.1,
                            heatindex_c: -1.4,
                            heatindex_f: 29.4,
                            dewpoint_c: -19.3,
                            dewpoint_f: -2.8,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 3.7,
                            gust_kph: 6,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735405200,
                            time: "2024-12-29 01:00",
                            temp_c: -1.8,
                            temp_f: 28.8,
                            is_day: 0,
                            condition: {
                                text: "Clear ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                code: 1000,
                            },
                            wind_mph: 1.3,
                            wind_kph: 2.2,
                            wind_degree: 305,
                            wind_dir: "NW",
                            pressure_mb: 1025,
                            pressure_in: 30.27,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 25,
                            cloud: 15,
                            feelslike_c: -1.8,
                            feelslike_f: 28.8,
                            windchill_c: -1.8,
                            windchill_f: 28.8,
                            heatindex_c: -1.8,
                            heatindex_f: 28.8,
                            dewpoint_c: -19.3,
                            dewpoint_f: -2.7,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 2.5,
                            gust_kph: 4,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735408800,
                            time: "2024-12-29 02:00",
                            temp_c: -2,
                            temp_f: 28.4,
                            is_day: 0,
                            condition: {
                                text: "Clear ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                code: 1000,
                            },
                            wind_mph: 1.8,
                            wind_kph: 2.9,
                            wind_degree: 299,
                            wind_dir: "WNW",
                            pressure_mb: 1025,
                            pressure_in: 30.26,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 25,
                            cloud: 22,
                            feelslike_c: -2,
                            feelslike_f: 28.4,
                            windchill_c: -2,
                            windchill_f: 28.4,
                            heatindex_c: -2,
                            heatindex_f: 28.4,
                            dewpoint_c: -19.3,
                            dewpoint_f: -2.7,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 3.3,
                            gust_kph: 5.3,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735412400,
                            time: "2024-12-29 03:00",
                            temp_c: -2,
                            temp_f: 28.3,
                            is_day: 0,
                            condition: {
                                text: "Clear ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                code: 1000,
                            },
                            wind_mph: 0.9,
                            wind_kph: 1.4,
                            wind_degree: 297,
                            wind_dir: "WNW",
                            pressure_mb: 1024,
                            pressure_in: 30.25,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 25,
                            cloud: 20,
                            feelslike_c: -2,
                            feelslike_f: 28.3,
                            windchill_c: -2,
                            windchill_f: 28.3,
                            heatindex_c: -2,
                            heatindex_f: 28.3,
                            dewpoint_c: -19.2,
                            dewpoint_f: -2.6,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 1.6,
                            gust_kph: 2.6,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735416000,
                            time: "2024-12-29 04:00",
                            temp_c: -2.1,
                            temp_f: 28.1,
                            is_day: 0,
                            condition: {
                                text: "Overcast ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                code: 1009,
                            },
                            wind_mph: 0.9,
                            wind_kph: 1.4,
                            wind_degree: 306,
                            wind_dir: "NW",
                            pressure_mb: 1024,
                            pressure_in: 30.24,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 26,
                            cloud: 100,
                            feelslike_c: -2.1,
                            feelslike_f: 28.1,
                            windchill_c: -2.1,
                            windchill_f: 28.1,
                            heatindex_c: -2.1,
                            heatindex_f: 28.1,
                            dewpoint_c: -19.2,
                            dewpoint_f: -2.5,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 1.6,
                            gust_kph: 2.6,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735419600,
                            time: "2024-12-29 05:00",
                            temp_c: -2.3,
                            temp_f: 27.8,
                            is_day: 0,
                            condition: {
                                text: "Overcast ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                code: 1009,
                            },
                            wind_mph: 0.7,
                            wind_kph: 1.1,
                            wind_degree: 21,
                            wind_dir: "NNE",
                            pressure_mb: 1023,
                            pressure_in: 30.21,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 26,
                            cloud: 100,
                            feelslike_c: -2.4,
                            feelslike_f: 27.8,
                            windchill_c: -2.4,
                            windchill_f: 27.8,
                            heatindex_c: -2.4,
                            heatindex_f: 27.8,
                            dewpoint_c: -19.1,
                            dewpoint_f: -2.4,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 1.2,
                            gust_kph: 1.9,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735423200,
                            time: "2024-12-29 06:00",
                            temp_c: -2.6,
                            temp_f: 27.4,
                            is_day: 0,
                            condition: {
                                text: "Partly Cloudy ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                code: 1003,
                            },
                            wind_mph: 1.1,
                            wind_kph: 1.8,
                            wind_degree: 36,
                            wind_dir: "NE",
                            pressure_mb: 1023,
                            pressure_in: 30.2,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 27,
                            cloud: 50,
                            feelslike_c: -2.6,
                            feelslike_f: 27.4,
                            windchill_c: -2.6,
                            windchill_f: 27.4,
                            heatindex_c: -2.6,
                            heatindex_f: 27.4,
                            dewpoint_c: -19.1,
                            dewpoint_f: -2.3,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 2,
                            gust_kph: 3.2,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735426800,
                            time: "2024-12-29 07:00",
                            temp_c: -2.9,
                            temp_f: 26.9,
                            is_day: 0,
                            condition: {
                                text: "Overcast ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                code: 1009,
                            },
                            wind_mph: 1.1,
                            wind_kph: 1.8,
                            wind_degree: 309,
                            wind_dir: "NW",
                            pressure_mb: 1023,
                            pressure_in: 30.21,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 27,
                            cloud: 100,
                            feelslike_c: -2.9,
                            feelslike_f: 26.9,
                            windchill_c: -2.9,
                            windchill_f: 26.9,
                            heatindex_c: -2.9,
                            heatindex_f: 26.9,
                            dewpoint_c: -19,
                            dewpoint_f: -2.2,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 2,
                            gust_kph: 3.2,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735430400,
                            time: "2024-12-29 08:00",
                            temp_c: -2.7,
                            temp_f: 27.1,
                            is_day: 1,
                            condition: {
                                text: "Overcast ",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                code: 1009,
                            },
                            wind_mph: 0.7,
                            wind_kph: 1.1,
                            wind_degree: 249,
                            wind_dir: "WSW",
                            pressure_mb: 1023,
                            pressure_in: 30.21,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 27,
                            cloud: 100,
                            feelslike_c: -2.7,
                            feelslike_f: 27.1,
                            windchill_c: -2.7,
                            windchill_f: 27.1,
                            heatindex_c: -2.7,
                            heatindex_f: 27.1,
                            dewpoint_c: -19,
                            dewpoint_f: -2.2,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 1.1,
                            gust_kph: 1.8,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735434000,
                            time: "2024-12-29 09:00",
                            temp_c: -2.1,
                            temp_f: 28.3,
                            is_day: 1,
                            condition: {
                                text: "Sunny",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                code: 1000,
                            },
                            wind_mph: 1.1,
                            wind_kph: 1.8,
                            wind_degree: 119,
                            wind_dir: "ESE",
                            pressure_mb: 1022,
                            pressure_in: 30.19,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 26,
                            cloud: 22,
                            feelslike_c: -2.1,
                            feelslike_f: 28.3,
                            windchill_c: -2.1,
                            windchill_f: 28.3,
                            heatindex_c: -2.1,
                            heatindex_f: 28.3,
                            dewpoint_c: -19,
                            dewpoint_f: -2.3,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 1.7,
                            gust_kph: 2.7,
                            uv: 0.2,
                        },
                        {
                            time_epoch: 1735437600,
                            time: "2024-12-29 10:00",
                            temp_c: -1.5,
                            temp_f: 29.4,
                            is_day: 1,
                            condition: {
                                text: "Overcast ",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                code: 1009,
                            },
                            wind_mph: 0.7,
                            wind_kph: 1.1,
                            wind_degree: 42,
                            wind_dir: "NE",
                            pressure_mb: 1022,
                            pressure_in: 30.18,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 24,
                            cloud: 100,
                            feelslike_c: -1.5,
                            feelslike_f: 29.4,
                            windchill_c: -1.5,
                            windchill_f: 29.4,
                            heatindex_c: -1.5,
                            heatindex_f: 29.4,
                            dewpoint_c: -19.1,
                            dewpoint_f: -2.3,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 0.9,
                            gust_kph: 1.5,
                            uv: 0.4,
                        },
                        {
                            time_epoch: 1735441200,
                            time: "2024-12-29 11:00",
                            temp_c: -0.6,
                            temp_f: 31,
                            is_day: 1,
                            condition: {
                                text: "Sunny",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                code: 1000,
                            },
                            wind_mph: 1.1,
                            wind_kph: 1.8,
                            wind_degree: 174,
                            wind_dir: "S",
                            pressure_mb: 1022,
                            pressure_in: 30.18,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 23,
                            cloud: 0,
                            feelslike_c: -0.6,
                            feelslike_f: 31,
                            windchill_c: -0.6,
                            windchill_f: 31,
                            heatindex_c: -0.6,
                            heatindex_f: 31,
                            dewpoint_c: -19.2,
                            dewpoint_f: -2.5,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 1.5,
                            gust_kph: 2.3,
                            uv: 0.8,
                        },
                        {
                            time_epoch: 1735444800,
                            time: "2024-12-29 12:00",
                            temp_c: 0.8,
                            temp_f: 33.4,
                            is_day: 1,
                            condition: {
                                text: "Sunny",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                code: 1000,
                            },
                            wind_mph: 0.9,
                            wind_kph: 1.4,
                            wind_degree: 200,
                            wind_dir: "SSW",
                            pressure_mb: 1021,
                            pressure_in: 30.14,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 20,
                            cloud: 0,
                            feelslike_c: 0.8,
                            feelslike_f: 33.4,
                            windchill_c: 0.8,
                            windchill_f: 33.4,
                            heatindex_c: 0.8,
                            heatindex_f: 33.4,
                            dewpoint_c: -19.5,
                            dewpoint_f: -3,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 1.1,
                            gust_kph: 1.7,
                            uv: 1.1,
                        },
                        {
                            time_epoch: 1735448400,
                            time: "2024-12-29 13:00",
                            temp_c: 1.7,
                            temp_f: 35,
                            is_day: 1,
                            condition: {
                                text: "Sunny",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                code: 1000,
                            },
                            wind_mph: 0.9,
                            wind_kph: 1.4,
                            wind_degree: 193,
                            wind_dir: "SSW",
                            pressure_mb: 1020,
                            pressure_in: 30.11,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 18,
                            cloud: 0,
                            feelslike_c: 1.7,
                            feelslike_f: 35,
                            windchill_c: 1.7,
                            windchill_f: 35,
                            heatindex_c: 1.7,
                            heatindex_f: 35,
                            dewpoint_c: -19.7,
                            dewpoint_f: -3.4,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 1.1,
                            gust_kph: 1.7,
                            uv: 1.1,
                        },
                        {
                            time_epoch: 1735452000,
                            time: "2024-12-29 14:00",
                            temp_c: 2.5,
                            temp_f: 36.6,
                            is_day: 1,
                            condition: {
                                text: "Sunny",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                code: 1000,
                            },
                            wind_mph: 1.8,
                            wind_kph: 2.9,
                            wind_degree: 154,
                            wind_dir: "SSE",
                            pressure_mb: 1018,
                            pressure_in: 30.07,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 17,
                            cloud: 0,
                            feelslike_c: 2.5,
                            feelslike_f: 36.6,
                            windchill_c: 2.5,
                            windchill_f: 36.6,
                            heatindex_c: 2.5,
                            heatindex_f: 36.6,
                            dewpoint_c: -19.9,
                            dewpoint_f: -3.9,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 2.2,
                            gust_kph: 3.6,
                            uv: 0.8,
                        },
                        {
                            time_epoch: 1735455600,
                            time: "2024-12-29 15:00",
                            temp_c: 4,
                            temp_f: 39.2,
                            is_day: 1,
                            condition: {
                                text: "Sunny",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                code: 1000,
                            },
                            wind_mph: 2.9,
                            wind_kph: 4.7,
                            wind_degree: 180,
                            wind_dir: "S",
                            pressure_mb: 1016,
                            pressure_in: 30,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 23,
                            cloud: 0,
                            feelslike_c: 2.6,
                            feelslike_f: 36.6,
                            windchill_c: 2.6,
                            windchill_f: 36.6,
                            heatindex_c: 3.6,
                            heatindex_f: 38.4,
                            dewpoint_c: -19.9,
                            dewpoint_f: -3.8,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 4,
                            gust_kph: 6.4,
                            uv: 0.4,
                        },
                        {
                            time_epoch: 1735459200,
                            time: "2024-12-29 16:00",
                            temp_c: 3.2,
                            temp_f: 37.7,
                            is_day: 1,
                            condition: {
                                text: "Sunny",
                                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                code: 1000,
                            },
                            wind_mph: 4.5,
                            wind_kph: 7.2,
                            wind_degree: 180,
                            wind_dir: "S",
                            pressure_mb: 1018,
                            pressure_in: 30.06,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 17,
                            cloud: 0,
                            feelslike_c: 1.2,
                            feelslike_f: 34.2,
                            windchill_c: 1.2,
                            windchill_f: 34.2,
                            heatindex_c: 3.2,
                            heatindex_f: 37.7,
                            dewpoint_c: -19.6,
                            dewpoint_f: -3.4,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 6.6,
                            gust_kph: 10.6,
                            uv: 0.1,
                        },
                        {
                            time_epoch: 1735462800,
                            time: "2024-12-29 17:00",
                            temp_c: 1.9,
                            temp_f: 35.4,
                            is_day: 0,
                            condition: {
                                text: "Clear ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                code: 1000,
                            },
                            wind_mph: 6,
                            wind_kph: 9.7,
                            wind_degree: 192,
                            wind_dir: "SSW",
                            pressure_mb: 1018,
                            pressure_in: 30.07,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 18,
                            cloud: 0,
                            feelslike_c: -1,
                            feelslike_f: 30.2,
                            windchill_c: -1,
                            windchill_f: 30.2,
                            heatindex_c: 1.9,
                            heatindex_f: 35.4,
                            dewpoint_c: -19.6,
                            dewpoint_f: -3.2,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 9.7,
                            gust_kph: 15.6,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735466400,
                            time: "2024-12-29 18:00",
                            temp_c: 1.2,
                            temp_f: 34.2,
                            is_day: 0,
                            condition: {
                                text: "Clear ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                code: 1000,
                            },
                            wind_mph: 4.7,
                            wind_kph: 7.6,
                            wind_degree: 203,
                            wind_dir: "SSW",
                            pressure_mb: 1018,
                            pressure_in: 30.08,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 20,
                            cloud: 0,
                            feelslike_c: -1.2,
                            feelslike_f: 29.9,
                            windchill_c: -1.2,
                            windchill_f: 29.9,
                            heatindex_c: 1.2,
                            heatindex_f: 34.2,
                            dewpoint_c: -19.2,
                            dewpoint_f: -2.6,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 8.1,
                            gust_kph: 13,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735470000,
                            time: "2024-12-29 19:00",
                            temp_c: 0.8,
                            temp_f: 33.4,
                            is_day: 0,
                            condition: {
                                text: "Clear ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                code: 1000,
                            },
                            wind_mph: 3.4,
                            wind_kph: 5.4,
                            wind_degree: 222,
                            wind_dir: "SW",
                            pressure_mb: 1019,
                            pressure_in: 30.08,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 21,
                            cloud: 0,
                            feelslike_c: -0.9,
                            feelslike_f: 30.4,
                            windchill_c: -0.9,
                            windchill_f: 30.4,
                            heatindex_c: 0.8,
                            heatindex_f: 33.4,
                            dewpoint_c: -19,
                            dewpoint_f: -2.3,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 6.2,
                            gust_kph: 9.9,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735473600,
                            time: "2024-12-29 20:00",
                            temp_c: 0.5,
                            temp_f: 32.9,
                            is_day: 0,
                            condition: {
                                text: "Clear ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                code: 1000,
                            },
                            wind_mph: 2.9,
                            wind_kph: 4.7,
                            wind_degree: 240,
                            wind_dir: "WSW",
                            pressure_mb: 1019,
                            pressure_in: 30.09,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 21,
                            cloud: 0,
                            feelslike_c: -0.9,
                            feelslike_f: 30.4,
                            windchill_c: -0.9,
                            windchill_f: 30.4,
                            heatindex_c: 0.5,
                            heatindex_f: 32.9,
                            dewpoint_c: -19.1,
                            dewpoint_f: -2.4,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 5.6,
                            gust_kph: 9,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735477200,
                            time: "2024-12-29 21:00",
                            temp_c: 0.3,
                            temp_f: 32.5,
                            is_day: 0,
                            condition: {
                                text: "Clear ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                code: 1000,
                            },
                            wind_mph: 2,
                            wind_kph: 3.2,
                            wind_degree: 316,
                            wind_dir: "NW",
                            pressure_mb: 1019,
                            pressure_in: 30.09,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 21,
                            cloud: 0,
                            feelslike_c: -0.3,
                            feelslike_f: 31.5,
                            windchill_c: -0.3,
                            windchill_f: 31.5,
                            heatindex_c: 0.3,
                            heatindex_f: 32.5,
                            dewpoint_c: -19.1,
                            dewpoint_f: -2.4,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 4,
                            gust_kph: 6.4,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735480800,
                            time: "2024-12-29 22:00",
                            temp_c: 0,
                            temp_f: 31.9,
                            is_day: 0,
                            condition: {
                                text: "Clear ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                code: 1000,
                            },
                            wind_mph: 2.7,
                            wind_kph: 4.3,
                            wind_degree: 348,
                            wind_dir: "NNW",
                            pressure_mb: 1019,
                            pressure_in: 30.1,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 22,
                            cloud: 0,
                            feelslike_c: -1.3,
                            feelslike_f: 29.7,
                            windchill_c: -1.3,
                            windchill_f: 29.7,
                            heatindex_c: 0,
                            heatindex_f: 31.9,
                            dewpoint_c: -18.9,
                            dewpoint_f: -2,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 5.4,
                            gust_kph: 8.7,
                            uv: 0,
                        },
                        {
                            time_epoch: 1735484400,
                            time: "2024-12-29 23:00",
                            temp_c: -0.2,
                            temp_f: 31.6,
                            is_day: 0,
                            condition: {
                                text: "Clear ",
                                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                code: 1000,
                            },
                            wind_mph: 3.1,
                            wind_kph: 5,
                            wind_degree: 338,
                            wind_dir: "NNW",
                            pressure_mb: 1019,
                            pressure_in: 30.1,
                            precip_mm: 0,
                            precip_in: 0,
                            snow_cm: 0,
                            humidity: 24,
                            cloud: 0,
                            feelslike_c: -1.9,
                            feelslike_f: 28.6,
                            windchill_c: -1.9,
                            windchill_f: 28.6,
                            heatindex_c: -0.2,
                            heatindex_f: 31.6,
                            dewpoint_c: -18,
                            dewpoint_f: -0.5,
                            will_it_rain: 0,
                            chance_of_rain: 0,
                            will_it_snow: 0,
                            chance_of_snow: 0,
                            vis_km: 10,
                            vis_miles: 6,
                            gust_mph: 6.5,
                            gust_kph: 10.5,
                            uv: 0,
                        },
                    ],
                },
            ],
        },
    },
};

export { weatherData_Minsk, weatherData_Pekin };
