const weatherData_Minsk = {
    currentAt_211224: {
        location: {
            name: "Minsk",
            region: "Minsk",
            country: "Belarus",
            lat: 53.9,
            lon: 27.5667,
            tz_id: "Europe/Minsk",
            localtime_epoch: 1734783641,
            localtime: "2024-12-21 15:20",
        },
        current: {
            last_updated_epoch: 1734783300,
            last_updated: "2024-12-21 15:15",
            temp_c: 0.7,
            temp_f: 33.3,
            is_day: 1,
            condition: {
                text: "Переменная облачность",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 224,
            wind_dir: "SW",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 33,
            feelslike_c: -3.5,
            feelslike_f: 25.7,
            windchill_c: -3.5,
            windchill_f: 25.7,
            heatindex_c: 0.7,
            heatindex_f: 33.3,
            dewpoint_c: -1.5,
            dewpoint_f: 29.3,
            vis_km: 10,
            vis_miles: 6,
            uv: 0.2,
            gust_mph: 14,
            gust_kph: 22.5,
        },
    },

    currentAt_281224: {
        location: {
            name: "Минск",
            region: "Minsk",
            country: "Беларусь",
            lat: 53.9,
            lon: 27.5667,
        },
        current: {
            last_updated: "2024-12-28 20:45",
            temp_c: 0.1,
            feelslike_c: -3.1,
            wind_kph: 9.7,
            humidity: 100,
            cloud: 75,
            is_day: 0,
            condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
            },
        },
    },
};

export { weatherData_Minsk };
